### ISSUE TITLE
hi, could you you share how this project works? 

### ISSUE THREAD

**Issue by luccahuguet** [ValeryStk/decentr_wg_communicator#1]
I just saw both decentr_wg_communicator  and WG_decentr_host processes running on my machine, and I have decentr installed.

So I would like to know more about them and if they are safe

**Comment by bagaman14** [comment]
Hello I'd like to have more info too. 
After a system crash, on windows restart, a black window popped up with process C:\DecentrWG_config\decentr_wg_communicator.exe saying:
Tunnel is uninstalled....OK
